### ISSUE TITLE
startsmartlabs/caddy-secrets repo does not exist anymore

### ISSUE THREAD

**Issue by sitic** [freman/caddy-reauth#21]
Not sure what happened to https://github.com/startsmartlabs/caddy-secrets and who to ping, but it 404s and leads to a build error when trying to build this plugin.

**Comment by bravecorvus** [comment]
@freman. I don’t think my patch is a good longterm solution because I just reuploaded the version of caddy-secrets I happened to have. I never confirmed that this was the newest version of the code (since smartsmartlabs took it down) and numerous changes/i provements could have occured since I last updated my copy. I suggest you either rewrite your code using a different library, or ask @fellou89 to add it back (since you are part of the group) in the long run. Cheers
